# Generated by Django 4.2.6 on 2023-12-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorApp', '0007_alter_purchaseorder_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
